[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[deploy.beforeStartCommand]]
command = "node prisma/fix-migration.js && npx prisma db push --skip-generate && npx prisma db seed"
